# Generated by Django 2.0.3 on 2018-04-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180422_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='not_employed_reason',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='not_employed_reason_other',
        ),
    ]
