# Generated by Django 2.0.3 on 2018-03-17 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, default='', max_length=100, verbose_name='degree/course')),
                ('year_graduated', models.IntegerField(blank=True, null=True)),
                ('student_num', models.CharField(blank=True, default='', max_length=50, verbose_name='student number')),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('contact_numbers', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
