# Generated by Django 2.0.3 on 2018-04-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employement_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Regular/Permanent'), (1, 'Contractual/Temporary/Casual'), (2, 'Self-employed'), (3, 'Unpaid family worker'), (4, 'Wage/Salary worker'), (5, 'Other')], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='employer_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='employer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status_other',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_currently_employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='nature_of_work',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='not_employed_reason',
            field=models.IntegerField(blank=True, choices=[(0, 'Advance/Further Study'), (1, 'Health-related reason(s)'), (2, 'No job opportunity'), (3, 'Family concern'), (4, 'Did not look for a job'), (5, 'Lack of work experience'), (6, 'Other')], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='not_employed_reason_other',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='present_job_position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_started',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
