# Generated by Django 2.0.3 on 2018-04-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180422_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unemployed_advance_study',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='unemployed_did_not_look',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='unemployed_family_concern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='unemployed_health',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='unemployed_lack_exp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='unemployed_no_job_opportunity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='unemployed_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='unemployed_other_reasons',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
