# Generated by Django 2.0.3 on 2018-05-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20180506_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='field_exam_year_passed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
